### ISSUE TITLE
Correct RR33/RR47 assignments

### ISSUE THREAD

**Issue by 4a-j** [smokris/usb-hid-usage#1]
The source code comment correctly notes that these two documents conflict. However, it incorrectly "resolves" the dispute in favor of RR47.

RR57 corrects the dispute by moving the codes defined in RR47.

https://usb.org/sites/default/files/hutrr57b-_correction_to_hutrr47_0.pdf

**Comment by smokris** [comment]
Ah, yeah, RR57 wasn't published until after I wrote this.  I just pushed c31c16a which updates it to include the revisions up through RR57.
